package newpackage;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tomas
 */
public class Janela extends javax.swing.JFrame {

	List<ExecCmd> execCmd = new ArrayList<>();
	DefaultListModel listModel = new DefaultListModel();

	/**
	 * Creates new form Janela
	 */
	public Janela() {
		initComponents();
		jList1.setModel(listModel);
		atualizarButton.setVisible(false);
		
		ImageIcon img = new ImageIcon("dwarf.png");
		this.setIconImage(img.getImage());
		
		Timer updateList = new Timer("atualiza-lista");
		TimerTask updateListTask = new UpdateListTask();
		updateList.scheduleAtFixedRate(updateListTask, 0, 333);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jList1 = new javax.swing.JList();
                fecharButton = new javax.swing.JButton();
                cmdTxtField = new javax.swing.JTextField();
                execButton = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                atualizarButton = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Gerenciador de Tarefas");
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setIconImages(null);

                jList1.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                jList1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                jList1MouseMoved(evt);
                        }
                });
                jScrollPane1.setViewportView(jList1);

                fecharButton.setText("Fechar");
                fecharButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                fecharButtonActionPerformed(evt);
                        }
                });

                execButton.setText("Executar");
                execButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                execButtonActionPerformed(evt);
                        }
                });

                jLabel1.setText("Lista de processos abertos");

                atualizarButton.setText("Atualizar");
                atualizarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                atualizarButtonActionPerformed(evt);
                        }
                });

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jTextArea1.setText("exemplos de comandos:\nnotepad\ncalc\npaint");
                jScrollPane2.setViewportView(jTextArea1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                                .addComponent(atualizarButton))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(fecharButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cmdTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                        .addComponent(execButton)
                                                        .addComponent(jScrollPane2))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(atualizarButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecharButton)
                                .addGap(8, 8, 8)
                                .addComponent(cmdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(execButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void execButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execButtonActionPerformed
		// botao executar
		ExecCmd cmd = new ExecCmd(cmdTxtField.getText());
		execCmd.add(cmd);
		cmd.start();

        }//GEN-LAST:event_execButtonActionPerformed

        private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
		// botao atualizar lista
		updateTable();
        }//GEN-LAST:event_atualizarButtonActionPerformed

        private void fecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharButtonActionPerformed
		// botao fechar processo
		int selecionado = jList1.getSelectedIndex();
		if (selecionado >= 0) {
			for (ExecCmd c : execCmd) {
				if (c.getIndex() == selecionado && !c.terminado()) {
					c.cancela();
					//updateTable();
					break;
				}
			}
		}
		//updateTable();
        }//GEN-LAST:event_fecharButtonActionPerformed

        private void jList1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseMoved
		// quando o mouse mover
		//updateTable();
        }//GEN-LAST:event_jList1MouseMoved

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			// tema padrao do sistema
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			// tema padrao cross plataform
//			UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
			//tema nimbus
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Janela().setVisible(true);
			}
		});
	}

	public synchronized void updateTable() {
		listModel.clear();
		int i = 0;
		for (ExecCmd e : execCmd) {
			if (e.isAlive()) {
				listModel.addElement(e.getCmd());
				e.setIndex(i);
				i++;
			}
		}
	}

	public class UpdateListTask extends TimerTask {

		@Override
		public void run() {
			int selecionado = jList1.getSelectedIndex();
			updateTable();
			if (selecionado >= 0) {
				jList1.setSelectedIndex(selecionado);
			}
		}
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton atualizarButton;
        private javax.swing.JTextField cmdTxtField;
        private javax.swing.JButton execButton;
        private javax.swing.JButton fecharButton;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JList jList1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        // End of variables declaration//GEN-END:variables
}
